AI_PPE_VIOLATION_TYPES = {
    "PERSON_WITHOUT_HELMET",
    "PERSON_WITHOUT_GLOVES",
    "PERSON_WITHOUT_BOOTS",
    "PERSON_WITHOUT_GOGGLES",
}

AI_PPE_REVIEW_TYPES = {
    "PPE_NOT_DETECTED_REVIEW",
}

AI_PPE_COMPLIANCE_TYPES = {
    "HELMET_DETECTED",
    "GLOVES_DETECTED",
    "BOOTS_DETECTED",
    "GOGGLES_DETECTED",
    "VEST_DETECTED",
}
